### ISSUE TITLE
Ubuntu error

### ISSUE THREAD

**Issue by marcelocecin** [open-rpa/node-red-contrib-tagui#2]
Hi
I'm running on Ubuntu for the first time
as attached, the extraction of the zip stopped
![photo_2021-05-31_15-03-53](https://user-images.githubusercontent.com/2955762/120228517-a7cef680-c221-11eb-9347-96a12fd56416.jpg)
and now when trying to run it happens the following steps:
<img width="165" alt="" src="https://user-images.githubusercontent.com/2955762/120228532-b1f0f500-c221-11eb-834d-46f2a0f11af3.png">
<img width="167" alt="" src="https://user-images.githubusercontent.com/2955762/120228558-c208d480-c221-11eb-95ad-a4e7a509d35d.png">
I am running the standard script

**Comment by marcelocecin** [comment]
now is another error
<img width="227" alt="" src="https://user-images.githubusercontent.com/2955762/120229229-0d6fb280-c223-11eb-86b3-28e23b7dbff0.png">

**Comment by skadefro** [comment]
is the prerequest installed ?
What error are you getting in the nodered console ?

```
RUN apt-get update \
    && apt-get install -y unzip wget gnupg python3-pip python3-venv php \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by marcelocecin** [comment]
yes, because I already used tagui on this machine, after I installed node-red

**Comment by skadefro** [comment]
@kensoh any idea ?

**Comment by kensoh** [comment]
Hi @skadefro and @marcelocecin, it looks like the issue of hangs at extraction is resolved.

I assume the error message is after processing by the Node-RED module. If yes, then the error message is from below. It happens when TagUI can't write to the tagui/src folder. This is suggesting for some reason, the user permissions of the Node-RED process can't create the files there. This is strange given the module extracts the folder there. Unless for some reason maybe the folder and files there have the immutable flag (can be checked with [lsattr command](https://www.tecmint.com/chattr-command-examples/))

```
tagui_parse.php:if (!touch('tagui_chrome.in')) die("ERROR - cannot initialise tagui_chrome.in\n");
tagui_parse.php:if (!touch('tagui_chrome.out')) die("ERROR - cannot initialise tagui_chrome.out\n");}
```

Assuming the extraction folder is ~/tagui, Marcelo you can explore the following ideas -
1. do a `lsattr` from ~/tagui/src folder to see if any immutable files (this means files can't be deleted even by root)
2. Run `~/tagui/src/tagui ~/tagui/flows/samples/1_google.tag` to see what happens when run manually
3. Double check that PHP is installed with `php -v` (it should be, given the error message you have)
4. Check if you are running as root. For Chrome/Chromium to run as root need `--disable-gpu` hack, for eg here -
https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

<blockquote><img src="https://colab.research.google.com/img/colab_favicon_256px.png" width="48" align="right"><div><strong><a href="https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing">Google Colaboratory</a></strong></div></blockquote>

**Comment by kensoh** [comment]
Hi @skadefro and @marcelocecin, it looks like the issue of hangs at extraction is resolved.

I assume the error message is after processing by the Node-RED module. If yes, then the error message is from below. It happens when TagUI can't write to the tagui/src folder. This is suggesting for some reason, the user permissions of the Node-RED process can't create the files there. This is strange given the module extracts the folder there. Unless for some reason maybe the folder and files there have the immutable flag (can be checked with [lsattr command](https://www.tecmint.com/chattr-command-examples/))

```
tagui_parse.php:if (!touch('tagui_chrome.in')) die("ERROR - cannot initialise tagui_chrome.in\n");
tagui_parse.php:if (!touch('tagui_chrome.out')) die("ERROR - cannot initialise tagui_chrome.out\n");}
```

Assuming the extraction folder is ~/tagui, Marcelo you can explore the following ideas -
1. do a `lsattr` from ~/tagui/src folder to see if any immutable files (this means files can't be deleted even by root)
2. Run `~/tagui/src/tagui ~/tagui/flows/samples/1_google.tag` to see what happens when run manually
3. Double check that PHP is installed with `php -v` (it should be, given the error message you have)
4. Check if you are running as root. For Chrome/Chromium to run as root need `--disable-gpu` hack, for eg here -
https://colab.research.google.com/drive/13bQO6G_hzE1teX35a3NZ4T5K-ICFFdB5?usp=sharing

**Comment by marcelocecin** [comment]
Hey guys
would it not be possible for node-red to try to recognize if tagui is installed in the path /usr/local/bin/tagui ?
according to documentation https://tagui.readthedocs.io/en/latest/setup.html
thanks

<blockquote><div><strong><a href="https://tagui.readthedocs.io/en/latest/setup.html">Installation — TagUI 6.14.0 documentation</a></strong></div></blockquote>

**Comment by skadefro** [comment]
That kind of makes sense ... But according to the guide tagui should be in ~/tagui ( and ~/.tagui for the python version ) so that is what we are checking .. but yes you could have placed tagui somewhere else and still registered the command in /usr/local/bin/tagui

**Comment by marcelocecin** [comment]
cdj@rpa:~/tagui$ php -v
PHP 7.4.18 (cli) (built: May  3 2021 11:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.18, Copyright (c), by Zend Technologies

**Comment by marcelocecin** [comment]
cdj@rpa:~/tagui$ lsattr
--------------e----- ./flows
--------------e----- ./src
--------------e----- ./docs
--------------e----- ./LICENSE.md
--------------e----- ./README.md

**Comment by marcelocecin** [comment]
when I run `~/tagui/src/tagui ~/tagui/flows/samples/1_google.tag` nothing happens

**Comment by kensoh** [comment]
Looks like PHP and immutable is not the cause. How does running manually result in?

2. Run ~/tagui/src/tagui ~/tagui/flows/samples/1_google.tag to see what happens when run manually

Also, today there is false-positive on tagui_chromep.php by AVG Anti-virus / Internet Security so it will delete the file. if you are using that, need to add manually to exception while waiting for my whitelisting application approval - https://github.com/kelaberetiv/TagUI/issues/1044

**Comment by marcelocecin** [comment]
when I run `~/tagui/src/tagui ~/tagui/flows/samples/1_google.tag` the script runs normally
<img width="588" alt="" src="https://user-images.githubusercontent.com/2955762/120365170-7d923d00-c2e4-11eb-87f1-3389378b45bb.png">

**Comment by marcelocecin** [comment]
now the error changed to: "Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)"
<img width="314" alt="" src="https://user-images.githubusercontent.com/2955762/120365598-07420a80-c2e5-11eb-86cd-4d9bd572aa05.png">

**Comment by kensoh** [comment]
I see, I have no other ideas to explore for now. Looks like this error appears when browser crash, but no idea why browser can crash - https://github.com/puppeteer/puppeteer/issues/4428

Hi Allan, for installation of TagUI, I think there are pros and cons of using user's installed TagUI. For RPA for Python, it is based on a forked version optimised for that package purpose, so I have to do an actual installation separate from user's. Doing separate has better control of the Node-RED module behaviour, but using user's one would be more intuitive for user.

**Comment by marcelocecin** [comment]
hey Ken, which platform uses puppeteer?

**Comment by kensoh** [comment]
Oh Puppeteer is popular tool by Google for automating websites, used by many. It's based in NodeJS.

The tool talks directly to Chrome using websocket and DevTools protocol, similar what TagUI does.

**Comment by marcelocecin** [comment]
I think I formulated my question wrongly: does the node-red or tagui use the puppeter?

**Comment by skadefro** [comment]
No.

**Comment by kensoh** [comment]
I see.. I was pointing that Chrome error message to highlight that similar issue is also happening for other apps.

For this situation, Marcelo you say that running from command prompt manually works - https://github.com/open-rpa/node-red-contrib-tagui/issues/2#issuecomment-852302252

But somehow, running from Node-RED fails with the websocket not open error - https://github.com/open-rpa/node-red-contrib-tagui/issues/2#issuecomment-852303632

I saw a Node-RED discussion thread mentioning SSL and IP address but I'm not familiar with Node-RED enough to understand if that is related to the issue here -
https://discourse.nodered.org/t/communication-send-error-error-websocket-is-not-open-readystate-3-closed/22172/14

Another popular open-source tool is also getting this error -
https://github.com/cypress-io/cypress/issues/5685

<blockquote><img src="https://aws1.discourse-cdn.com/business6/uploads/nodered/original/2X/4/4e31e726f516faf3d28cb905ee61b6165a0465a3.svg" width="48" align="right"><div><img src="https://aws1.discourse-cdn.com/business6/uploads/nodered/optimized/1X/598c4a26af3e3272e341a28c9f4adb5c75c8f5dc_2_32x32.png" height="14"> Node-RED Forum</div><div><strong><a href="https://discourse.nodered.org/t/communication-send-error-error-websocket-is-not-open-readystate-3-closed/22172/14">"Communication send error: Error: WebSocket is not open: readyState 3 (CLOSED)</a></strong></div><div>That's why we need to see the startup logs.</div></blockquote>

**Comment by marcelocecin** [comment]
node-red runs tagui in which way?

**Comment by kensoh** [comment]
It looks no difference to me from the source code (just spawning a child process from NodeJS to run TagUI) https://github.com/open-rpa/node-red-contrib-tagui/blob/19f9319740156b10a0cd7e6ecf8ecb2c686ff6f8/src/tagui.ts#L114 but will leave Allan to comment more.

**Comment by marcelocecin** [comment]
would it be possible to get the value of the taguiexe variable?
is it possible to get more complete logs about this run?

**Comment by skadefro** [comment]
> It looks no difference to me from the source code (just spawning a child process from NodeJS to run TagUI)
> 
> https://github.com/open-rpa/node-red-contrib-tagui/blob/19f9319740156b10a0cd7e6ecf8ecb2c686ff6f8/src/tagui.ts#L114
> 
> but will leave Allan to comment more.

Yes, it simply runs tagui from the install folder in ~

**Comment by skadefro** [comment]
> would it be possible to get the value of the taguiexe variable?

Could add it to the msg object, but what is the use case where you would need that ?
> is it possible to get more complete logs about this run?

If you disable the "Quiet" option, you will get all the output from the live session from the second output.

**Comment by kensoh** [comment]
For taguiexe variable it looks like something very simple, just running tagui command - 

https://github.com/open-rpa/node-red-contrib-tagui/blob/19f9319740156b10a0cd7e6ecf8ecb2c686ff6f8/src/tagui.ts#L53

**Comment by marcelocecin** [comment]
hi Allan, how do I disable the "Quiet" option ?
thank you !

**Comment by skadefro** [comment]
Remove the check mark ?
![image](https://user-images.githubusercontent.com/4155937/121810641-f2a92f00-cc61-11eb-824c-7676823ad752.png)

**Comment by kensoh** [comment]
Adding on, TagUI uses port 9222 to connect to Chrome using websocket. But I don't think NodeRED uses this port and the reason for the websocket error message is due to such conflict from NodeRED. Because I can run Node-RED TagUI ok on my macOS. I have previously tried running many times and did not trigger this error message you shared here - https://github.com/open-rpa/node-red-contrib-tagui/issues/2#issuecomment-852303632

```
--remote-debugging-port=9222
```

**Comment by marcelocecin** [comment]
is possible to use https://github.com/tebelorg/RPA-Python instead https://github.com/kelaberetiv/TagUI ?

<blockquote><img src="https://repository-images.githubusercontent.com/178592227/84c4cd00-4db9-11ea-9843-d433a358263c" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/tebelorg/RPA-Python">tebelorg/RPA-Python</a></strong></div><div>Python package for doing RPA. Contribute to tebelorg/RPA-Python development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/75694548/a2874080-74a9-11eb-9c05-3e4802d4d30e" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/kelaberetiv/TagUI">kelaberetiv/TagUI</a></strong></div><div>Free RPA tool by AI Singapore. Contribute to kelaberetiv/TagUI development by creating an account on GitHub.</div></blockquote>

**Comment by skadefro** [comment]
Not for the TagUI node, since it depends on live mode.
But there are several ways you can use the RPA python package from NodeRED.
The most easy, would be to enable [function_external_modules](https://nodered.org/docs/user-guide/writing-functions#using-the-functionexternalmodules-option) in nodered settings. This allows you to define a list of NPM modules you want access to, on the function node.
Here you can then install a package to call python. In my examples I use [PythonShell](https://github.com/extrabacon/python-shell) and then using exec nodes you can trigger an install of the RPA pacakge if you don't have it installed already.
The above is what i completly automate using my TagUI-NodeRED docker image 

( using [this guide](https://www.linkedin.com/pulse/unattended-browser-automation-allan-zimmermann) that uses an image made from this [Dockerfile](https://github.com/open-rpa/openflow/blob/master/OpenFlowNodeRED/Dockerfiletagui) and can be used with [these example files](https://github.com/open-rpa/examples-files/tree/master/nodered-tagui-image-search). )

**Comment by marcelocecin** [comment]
ok thanks Allan

**Comment by marcelocecin** [comment]
Hi guys
just an update of an error that happened to me on MAC OS
when I installed the plugin through the Palette, the executables in the CASPERJS and PHANTOMJS folders were corrupted
later I will test if this also occurs on Ubuntu
thanks

**Comment by kensoh** [comment]
Thanks Marcelo, when I look at the code, it extracts to user home directory. On mac that would be ~ folder.

https://github.com/open-rpa/node-red-contrib-tagui/blob/19f9319740156b10a0cd7e6ecf8ecb2c686ff6f8/src/tagui.ts#L50

If users has an existing installation at ~/tagui folder yes I think this package might have a remote possibility overwrite there.

However, there is already condition check that should have flagged out an existing installation and should not overwrite.

https://github.com/open-rpa/node-red-contrib-tagui/blob/19f9319740156b10a0cd7e6ecf8ecb2c686ff6f8/src/tagui.ts#L55

**Comment by skadefro** [comment]
As @kensoh points out, if you already have tagui installed in the ~/tagui it will not touch it.
