### ISSUE TITLE
Multiple Inputs

### ISSUE THREAD

**Issue by ecymb1** [open-rpa/node-red-contrib-tagui#4]
I read that upto 8 inputs could be passed at a time (p1-p8). 
Could someone please explain how to do so?
P.S: I know how to pass one variable.

Any help would be appreciated.

**Comment by skadefro** [comment]
Set msg.payload to an array, then first item becomes p1, second item p2 etc.

**Comment by ecymb1** [comment]
Hello Mr. Allan, 

Thanks for your quick reply. 

When I send an array [SN1, 1], it gets processed as one object (only p1).
Could you please share an example?

**Comment by skadefro** [comment]
Maybe a stupid example, but just wanted to make something quickly
as you can see, this types the 2nd parameter in the google search first, then the first. Illustrating it knows the difference between the two values
```
[{"id":"320d0813d5588250","type":"tagui tagui","z":"de12dee8.377a1","name":"","headless":false,"nobrowser":false,"param":true,"quiet":true,"script":"https://www.google.dk/imghp?hl=en&ogbl\ntype q as `p2`\nwait 2 sec\ntype q as `p1`\nwait 2 sec","x":450,"y":220,"wires":[["3e3171fef080efc1"],["82dfc4fd2a10f84f"],["ed09bc24c7920544"]]},{"id":"fdb6e7efb30381ce","type":"inject","z":"de12dee8.377a1","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":220,"wires":[["5b64bf2c16e3b73a"]]},{"id":"5b64bf2c16e3b73a","type":"function","z":"de12dee8.377a1","name":"","func":"msg.payload = [1, 2, 3]\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":300,"y":220,"wires":[["320d0813d5588250"]]},{"id":"3e3171fef080efc1","type":"debug","z":"de12dee8.377a1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":610,"y":200,"wires":[]},{"id":"82dfc4fd2a10f84f","type":"debug","z":"de12dee8.377a1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":610,"y":240,"wires":[]},{"id":"ed09bc24c7920544","type":"debug","z":"de12dee8.377a1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":610,"y":280,"wires":[]},{"id":"cef3b9ba6dd75815","type":"tagui tagui","z":"de12dee8.377a1","name":"","headless":false,"nobrowser":false,"param":true,"quiet":true,"script":"https://www.google.dk/imghp?hl=en&ogbl\ntype q as `p2`\nwait 2 sec\ntype q as `p1`\n\n","x":450,"y":340,"wires":[["3d33f11ff078e7bb"],["53c30dd85901895e"],["548a7c474538229e"]]},{"id":"175c20bec7206d3e","type":"inject","z":"de12dee8.377a1","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":340,"wires":[["f8ba1b74aad2e2f0"]]},{"id":"f8ba1b74aad2e2f0","type":"function","z":"de12dee8.377a1","name":"","func":"msg.payload = ['Hi-dad', 'Hi-mom', 'hi-sister']\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":300,"y":340,"wires":[["cef3b9ba6dd75815"]]},{"id":"3d33f11ff078e7bb","type":"debug","z":"de12dee8.377a1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":610,"y":320,"wires":[]},{"id":"53c30dd85901895e","type":"debug","z":"de12dee8.377a1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":610,"y":360,"wires":[]},{"id":"548a7c474538229e","type":"debug","z":"de12dee8.377a1","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":590,"y":400,"wires":[]}]
```
If a paramter has space in it, it fails with error 255, is that a know issue @kensoh ? ( right now it's adding " around the string, but i just tested without, but I still get an error if a parameter has spaces in it )

**Comment by ecymb1** [comment]
Dear Mr. Allan,

Indeed, the space does cause an error (255). Otherwise, it works perfectly. 
Thanks a lot for your support and guidance. Highly appreciate it.

**Comment by kensoh** [comment]
I didn't get error 255, for above even when changing the bottom group 'hi-dad' to 'hi dad'. However, I can elaborate some design of the tagui command for more idea on passing parameters. Other than the filename parameter, the other parameters p1 to p8 are recognised by a space.

So if below is passed to TagUI -
```
tagui flow.tag "cute kitten"
```
Inside TagUI, p1 will be `"cute` and p2 will be `kitten"`

If below is passed to TagUI -
```
tagui flow.tag cute kitten
```
Inside TagUI, p1 will be `cute` and p2 will be `kitten`

Some ideas on improving passing parameters from this module and taking in of parameters from TagUI -

1. perhaps the module can send without the double quotes, otherwise the input data would be 'inaccurate' with the opening " for p1 and closing " for p2. and if it is 1 word, i think TagUI will receive p1 as "value" instead of value

2. From the TagUI script in the node, user can check to build back the whole string if the string is needed as 1 single string instead of each parameter p1 to p8 -
```
parameters = ''
echo `p1` `p2` `p3`
if p1
    parameters += p1 + ' '
if p2
    parameters += p2 + ' '
if p3
    parameters += p3 + ' '
echo `parameters`
```

2 other points to add is maybe the error Allan encountered and I don't have is because of some adjacent fixes in the last couple of months. An idea to consider is downloading the v6.46 and then typing `tagui update` to sync to the latest version - https://tagui.readthedocs.io/en/latest/setup.html

The other point is if user wants to pass in more sophisticated data, user can create a JSON string from the data object from input using eg `JSON.stringify({name: "John", age: 30, city: "New York"})`, save it to a text file for eg jsondata.txt, then in the TagUI node the script could use the following to convert back into an object.

```
load jsondata.txt to json_text
json_object = JSON.parse(json_text)
```

<blockquote><div><strong><a href="https://tagui.readthedocs.io/en/latest/setup.html">Installation — TagUI 6.46.0 documentation</a></strong></div></blockquote>

**Comment by skadefro** [comment]
Hey Ken.
I updated to v6.46 but still get an error when using, still error
then tried tagui update, still error
So only difference is the " that you need in dos to send parameter with spaces. And sure enough it fails if i add "
![image](https://user-images.githubusercontent.com/4155937/128628822-3eb347cb-a475-4f02-9f5a-bd334a54e5d8.png)

**Comment by skadefro** [comment]
And i just read what you wrote more carfully, you (semi)clearly states, tagui does NOT support parameters containing spaces ( maybe do to the issue with " ? ) ... never mind then, I guess using a text file/json file as middle man is the way to go for people that need more complex data exchanged :-)

**Comment by kensoh** [comment]
Hi Allan :) Thanks for your inputs! Looks like this issue is specific to Windows (it is ok on my Mac). What do you think of Node-RED TagUI module to pass parameters to tagui.cmd / tagui without the enclosing double quotes?

Having the double quotes seems to have a risk of breaking execution while not adding benefit for users since TagUI from the tagui.cmd batch script will treat any space as a separator for the next parameter.

What happens is tagui.cmd passes the parameters to the CasperJS process, which maps into the different parameters within TagUI JavaScript environment.

But yes, recommend saving data to a file and pass that filename as parameter to be open in TagUI.

**Comment by kensoh** [comment]
PS - I've just confirmed I can replicate on Windows. Using double quotes to enclose the parameters create the errors you shared above. But ok on Mac. Sorry, earlier I was out and only have my Mac with me and wasn't able to replicate the error.

**Comment by skadefro** [comment]
I have update package to download v6.46 and added an "update" option on the node, to get latest version

**Comment by kensoh** [comment]
Thanks Allan! I look through the code diffs. I assume the current iteration won't send parameters with double quotes "", otherwise the module will fail execution if there are spaces in provided parameters from user or other nodes.
